/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.keycoil;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author camer
 */
//This is the Home screen
public class Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    public Home() throws IOException {
        initComponents();
        
        //Displays the username, average WPM, highest WPM, number of games played, and profile picture
        usernameLabel.setText(Profile.username);
        
        System.out.println(Profile.username);
        
        this.setLayout(new BorderLayout());
        this.setSize(585, 325);
        this.setVisible(true);
        this.setFocusable(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        //this.getContentPane().setBackground(Color.darkGray);
        this.revalidate();
        
        BufferedImage image = ImageIO.read(new File(Profile.pfp.getPath()));
        pfpLabel = new JLabel(new ImageIcon(image));
        
        pfpLabel.setMaximumSize(new Dimension(300, 300));
        
        this.getContentPane().add(pfpLabel);
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        draw(g);
    }
    
    public void draw(Graphics g){
        g.setFont(new Font("MV Boli", Font.BOLD, 50));

        g.drawString(Profile.username, 20, 100);
        g.setFont(new Font("MV Boli", Font.PLAIN, 20));
        
        if(Profile.numGames > 0){
            g.drawString("Average WPM: " + (int) (Profile.avgWPM / Profile.numGames), 20, 150);
            g.drawString("Highest WPM: " + (int) Profile.highestWPM, 20, 200);
            g.drawString("Number of Games Played: "+ Profile.numGames, 20, 250);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        try{
            BufferedImage image = ImageIO.read(new File(Profile.pfp.getPath()));
            ImageIcon cuh = new ImageIcon(Profile.pfp.getPath());
            pfpLabel = new javax.swing.JLabel();

            usernameLabel.setText(" ");

            pfpLabel.setIcon(cuh);
        }
        catch(IOException e){
            System.out.println(e);
        }
        pfpLabel.setText("pfpLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 77, Short.MAX_VALUE)
                .addComponent(pfpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(usernameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(pfpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pfpLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
