/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.keycoil;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author camer
 */
//This class is used to sign into an already existing profile
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterUsernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterUsernameLabel.setText("Enter Username");

        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterUsernameLabel)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(signInButton)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(enterUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signInButton)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
        if(usernameTextField.getText().equals("")){ //Makes sure the field has been filled
            JOptionPane.showMessageDialog(null, "Please enter all of the fields", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                //System.out.println("src\\" + usernameTextField.getText() + ".txt");
                Scanner file = new Scanner(new File("src\\" + usernameTextField.getText() + ".txt")); //Tries to find a file with the correct username
                Profile.username = file.nextLine(); //Sets the variables of the profile class to the data stored in the file
                Profile.pfp = new File(file.nextLine());
                Profile.avgWPM = Double.parseDouble(file.nextLine());
                Profile.highestWPM = Double.parseDouble(file.nextLine());
                Profile.numGames = Integer.parseInt(file.nextLine());
                
                setVisible(false);
            
                try {
                    
                    Typo typo = new Typo(); //Instantiates the Typo class again to be edited later
                    WordWhackers main = new WordWhackers(); //Calls the main menu of the project after logging
                    Typo.typos.put("a", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("b", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("c", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("d", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("e", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("f", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("g", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("h", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("i", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("j", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("k", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("l", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("m", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("n", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("o", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("p", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("q", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("r", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("s", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("t", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("u", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("v", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("w", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("x", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("y", Integer.parseInt(file.nextLine()));
                    Typo.typos.put("z", Integer.parseInt(file.nextLine()));
                    
                    //Saves all of the user's typo data from the file

                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) { //Throws an error pop up if the username could not be found
                JOptionPane.showMessageDialog(null, "Could not find profile", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_signInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterUsernameLabel;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
